---
- name: check for pf.conf existence
  file:
    path: /etc/pf.conf
  register: pfexists
  failed_when: False

- name: Ensure anchors files exists
  file:
    dest: '{{ item }}'
    state: touch
  with_items:
    - /etc/pf.anchor.nat-jail.conf
    - /etc/pf.anchor.rdr-jail.conf
    - /etc/pf.anchor.rules-jail.conf

- name: Copy pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    mode: 0644
  notify:
    - Reload pf
  when: pfexists.state == "absent"

- name: enable pf
  service:
    name: '{{ item }}'
    state: enabled
  with_items:
    - pflog
    - pf

